backend/tracim_backend/models/applications.py, backend/tracim_backend/models/contents.py, backend/tracim_backend/tests/__init__.py, backend/tracim_backend/tests/functional/test_contents.py, backend/tracim_backend/tests/functional/test_system.py, backend/tracim_backend/tests/functional/test_user.py, backend/tracim_backend/tests/functional/test_workspaces.py, backend/tracim_backend/views/core_api/schemas.py
=> [#688] Fix naming rule for applications and content associated

backend/tracim_backend/models/context_models.py, backend/tracim_backend/tests/functional/test_workspaces.py, backend/tracim_backend/views/core_api/schemas.py
=> parent_id can be null/none for content creation endpoint

backend/tracim_backend/views/contents_api/comment_controller.py, backend/tracim_backend/views/contents_api/file_controller.py, backend/tracim_backend/views/contents_api/html_document_controller.py, backend/tracim_backend/views/contents_api/threads_controller.py, backend/tracim_backend/views/core_api/user_controller.py, backend/tracim_backend/views/core_api/workspace_controller.py
related to tracim/tracim#751 issue
=> Allow get deleted or archived content with individual content endpoint

backend/tracim_backend/lib/core/userworkspace.py, backend/tracim_backend/models/context_models.py, backend/tracim_backend/tests/functional/test_workspaces.py, backend/tracim_backend/views/core_api/schemas.py, backend/tracim_backend/views/core_api/workspace_controller.py
=> add do_notify param to endpoints for roles

backend/tracim_backend/lib/utils/utils.py, backend/tracim_backend/tests/functional/test_system.py, backend/tracim_backend/views/core_api/schemas.py, backend/tracim_backend/views/core_api/system_controller.py
related to tracim/tracim#833.
Add endpoint for registered user about list of timezones.
=> add timezones list endpoint

backend/tracim_backend/lib/utils/cors.py
=> add variable allow_origin cors response

backend/tracim_backend/lib/core/content.py, backend/tracim_backend/models/context_models.py, backend/tracim_backend/tests/functional/test_contents.py, backend/tracim_backend/views/core_api/schemas.py
=> add pdf_available param in file endpoint

frontend/dist/index.mak
=> add global js var for primary color in index.mak

backend/tracim_backend/app_models/contents.py, backend/tracim_backend/lib/core/content.py
=> content creation do not need anymore folder content_type

backend/.gitignore, backend/development.ini.sample
=> typo session_lock ignored_folder name

backend/tracim_backend/lib/core/user.py
=> better exception for notification not send

backend/tracim_backend/tests/functional/test_user.py, backend/tracim_backend/views/core_api/user_controller.py
=> rename route for notification activation/deactivation

backend/development.ini.sample
=> add hapic_debug_mode by default

backend/tracim_backend/config.py
=> restore_previous_application order in app_list

backend/tracim_backend/models/data.py, backend/tracim_backend/tests/functional/test_contents.py, backend/tracim_backend/tests/library/test_content_api.py
=> set_label_wenever_file_data_is_updated

frontend/package.json
Fix some frontend build issue.
=> Fix frontend build : do not use ssh and update webpack

backend/tracim_backend/lib/mail_notifier/notifier.py, backend/tracim_backend/lib/utils/utils.py
Ref: https://github.com/tracim/tracim/issues/986
=> Change used url for lost password email

backend/tracim_backend/models/context_models.py, backend/tracim_backend/tests/functional/test_contents.py, backend/tracim_backend/views/core_api/schemas.py
related to https://github.com/tracim/tracim/issues/958
=> add file_extension in file content endpoint

backend/tests_configs.ini, backend/tracim_backend/tests/functional/test_frontend.py
=> add simple test for frontend serve

backend/tracim_backend/app_models/applications.py, backend/tracim_backend/app_models/workspace_menu_entries.py, backend/tracim_backend/config.py, backend/tracim_backend/views/core_api/schemas.py
This is the first (backend) part of the fix of issue https://github.com/tracim/tracim/issues/1027
=> remove `/#` prefix on routes configured for frontend

backend/tracim_backend/tests/functional/test_workspaces.py, backend/tracim_backend/views/core_api/workspace_controller.py
=> add admin access to individual workspace_endpoints

backend/tracim_backend/templates/mail/created_account_body_html.mak
=> remove useless space in email template

backend/tracim_backend/models/context_models.py, backend/tracim_backend/tests/functional/test_workspaces.py, backend/tracim_backend/views/core_api/schemas.py, backend/tracim_backend/views/core_api/workspace_controller.py
=> strictly separate email field form public_name field

backend/tracim_backend/command/database.py, backend/tracim_backend/tests/__init__.py
=> remove most logging in command test

backend/tracim_backend/lib/core/content.py, backend/tracim_backend/tests/functional/test_comments.py
=> disallow to add comment to not editable content

backend/tracim_backend/lib/core/user.py
=> hack to avoid issue with email recipient

backend/tracim_backend/models/context_models.py
=> fix issue with contentApi and deleted/archived cotnent in context_model
